//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Epay3.Module.BusinessObjects.EpayDataModel
{

    [DeferredDeletion(false)]
    public partial class Bill : XPObject
    {
        int fYear;
        public int Year
        {
            get { return fYear; }
            set { SetPropertyValue<int>(nameof(Year), ref fYear, value); }
        }
        int fMonth;
        public int Month
        {
            get { return fMonth; }
            set { SetPropertyValue<int>(nameof(Month), ref fMonth, value); }
        }
        decimal fAmount;
        public decimal Amount
        {
            get { return fAmount; }
            set { SetPropertyValue<decimal>(nameof(Amount), ref fAmount, value); }
        }
        DateTime fDueDate;
        public DateTime DueDate
        {
            get { return fDueDate; }
            set { SetPropertyValue<DateTime>(nameof(DueDate), ref fDueDate, value); }
        }
        DateTime fPaymentDate;
        public DateTime PaymentDate
        {
            get { return fPaymentDate; }
            set { SetPropertyValue<DateTime>(nameof(PaymentDate), ref fPaymentDate, value); }
        }
    }

}
