//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Epay3.Module.BusinessObjects.EpayDataModel
{

    [DeferredDeletion(false)]
    public partial class CalendarDay : XPObject
    {
        DateTime fDate;
        public DateTime Date
        {
            get { return fDate; }
            set { SetPropertyValue<DateTime>(nameof(Date), ref fDate, value); }
        }
        System.DayOfWeek fDayOfWeek;
        public System.DayOfWeek DayOfWeek
        {
            get { return fDayOfWeek; }
            set { SetPropertyValue<System.DayOfWeek>(nameof(DayOfWeek), ref fDayOfWeek, value); }
        }
        int fDay;
        public int Day
        {
            get { return fDay; }
            set { SetPropertyValue<int>(nameof(Day), ref fDay, value); }
        }
        int fYear;
        public int Year
        {
            get { return fYear; }
            set { SetPropertyValue<int>(nameof(Year), ref fYear, value); }
        }
        bool fWeekend;
        public bool Weekend
        {
            get { return fWeekend; }
            set { SetPropertyValue<bool>(nameof(Weekend), ref fWeekend, value); }
        }
        [Association(@"CalendarDayReferencesCalendar")]
        public XPCollection<Calendar> Calendars { get { return GetCollection<Calendar>(nameof(Calendars)); } }
    }

}
