//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Epay3.Module.BusinessObjects.EpayDataModel
{

    [DeferredDeletion(false)]
    public partial class Card : XPObject
    {
        string fCardNo;
        [DevExpress.Persistent.Validation.RuleUniqueValue, Indexed(Unique = true)]
        public string CardNo
        {
            get { return fCardNo; }
            set { SetPropertyValue<string>(nameof(CardNo), ref fCardNo, value); }
        }
        bool fActive;
        public bool Active
        {
            get { return fActive; }
            set { SetPropertyValue<bool>(nameof(Active), ref fActive, value); }
        }
        Customer fCustomer;
        [Association(@"CardReferencesCustomer")]
        public Customer Customer
        {
            get { return fCustomer; }
            set { SetPropertyValue<Customer>(nameof(Customer), ref fCustomer, value); }
        }
        int? fMinimumBalanceLimit;
        public int? MinimumBalanceLimit
        {
            get { return fMinimumBalanceLimit; }
            set { SetPropertyValue<int?>(nameof(MinimumBalanceLimit), ref fMinimumBalanceLimit, value); }
        }
        bool fReturnable;
        public bool Returnable
        {
            get { return fReturnable; }
            set { SetPropertyValue<bool>(nameof(Returnable), ref fReturnable, value); }
        }
        [Association(@"TransactionReferencesCard")]
        public XPCollection<Transaction> Transactions { get { return GetCollection<Transaction>(nameof(Transactions)); } }
        [Association(@"LocationCardReferencesCard")]
        public XPCollection<LocationCard> LocationCards { get { return GetCollection<LocationCard>(nameof(LocationCards)); } }
    }

}
