//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Epay3.Module.BusinessObjects.EpayDataModel
{

    [DeferredDeletion(false)]
    public partial class Customer : XPObject
    {
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        string fCitizenshipNumber;
        public string CitizenshipNumber
        {
            get { return fCitizenshipNumber; }
            set { SetPropertyValue<string>(nameof(CitizenshipNumber), ref fCitizenshipNumber, value); }
        }
        string fPhone;
        public string Phone
        {
            get { return fPhone; }
            set { SetPropertyValue<string>(nameof(Phone), ref fPhone, value); }
        }
        string fUserName;
        public string UserName
        {
            get { return fUserName; }
            set { SetPropertyValue<string>(nameof(UserName), ref fUserName, value); }
        }
        string fPassword;
        public string Password
        {
            get { return fPassword; }
            set { SetPropertyValue<string>(nameof(Password), ref fPassword, value); }
        }
        string fEmail;
        public string Email
        {
            get { return fEmail; }
            set { SetPropertyValue<string>(nameof(Email), ref fEmail, value); }
        }
        string fToken;
        [Size(1000)]
        [MemberDesignTimeVisibility(false)]
        public string Token
        {
            get { return fToken; }
            set { SetPropertyValue<string>(nameof(Token), ref fToken, value); }
        }
        string fTeam;
        public string Team
        {
            get { return fTeam; }
            set { SetPropertyValue<string>(nameof(Team), ref fTeam, value); }
        }
        string fNotificationToken;
        [MemberDesignTimeVisibility(false)]
        [DevExpress.Persistent.Base.VisibleInListView(false)]
        public string NotificationToken
        {
            get { return fNotificationToken; }
            set { SetPropertyValue<string>(nameof(NotificationToken), ref fNotificationToken, value); }
        }
        [Association(@"CardReferencesCustomer")]
        public XPCollection<Card> Cards { get { return GetCollection<Card>(nameof(Cards)); } }
        [Association(@"OrderReferencesCustomer")]
        public XPCollection<Order> Orders { get { return GetCollection<Order>(nameof(Orders)); } }
        [Association(@"RegistrationRequestReferencesCustomer")]
        public XPCollection<RegistrationRequest> RegistrationRequests { get { return GetCollection<RegistrationRequest>(nameof(RegistrationRequests)); } }
        [Association(@"ItemPermissionReferencesCustomer")]
        public XPCollection<ItemPermission> ItemPermissions { get { return GetCollection<ItemPermission>(nameof(ItemPermissions)); } }
        [Association(@"MessageReferencesCustomer")]
        public XPCollection<Message> Messages { get { return GetCollection<Message>(nameof(Messages)); } }
    }

}
