//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Epay3.Module.BusinessObjects.EpayDataModel
{

    public partial class DeviceRegistration : XPObject
    {
        DateTime fDate;
        public DateTime Date
        {
            get { return fDate; }
            set { SetPropertyValue<DateTime>(nameof(Date), ref fDate, value); }
        }
        string fSourceAddress;
        public string SourceAddress
        {
            get { return fSourceAddress; }
            set { SetPropertyValue<string>(nameof(SourceAddress), ref fSourceAddress, value); }
        }
        bool fSuccess;
        public bool Success
        {
            get { return fSuccess; }
            set { SetPropertyValue<bool>(nameof(Success), ref fSuccess, value); }
        }
        string fSerial;
        public string Serial
        {
            get { return fSerial; }
            set { SetPropertyValue<string>(nameof(Serial), ref fSerial, value); }
        }
        string fToken;
        public string Token
        {
            get { return fToken; }
            set { SetPropertyValue<string>(nameof(Token), ref fToken, value); }
        }
    }

}
