//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Epay3.Module.BusinessObjects.EpayDataModel
{

    [DeferredDeletion(false)]
    public partial class DeviceLogin : XPObject
    {
        DateTime fDate;
        public DateTime Date
        {
            get { return fDate; }
            set { SetPropertyValue<DateTime>(nameof(Date), ref fDate, value); }
        }
        string fSerial;
        public string Serial
        {
            get { return fSerial; }
            set { SetPropertyValue<string>(nameof(Serial), ref fSerial, value); }
        }
        string fSourceAddress;
        public string SourceAddress
        {
            get { return fSourceAddress; }
            set { SetPropertyValue<string>(nameof(SourceAddress), ref fSourceAddress, value); }
        }
        string fUserNameReceived;
        public string UserNameReceived
        {
            get { return fUserNameReceived; }
            set { SetPropertyValue<string>(nameof(UserNameReceived), ref fUserNameReceived, value); }
        }
        string fPasswordReceived;
        public string PasswordReceived
        {
            get { return fPasswordReceived; }
            set { SetPropertyValue<string>(nameof(PasswordReceived), ref fPasswordReceived, value); }
        }
        string fSuccess;
        public string Success
        {
            get { return fSuccess; }
            set { SetPropertyValue<string>(nameof(Success), ref fSuccess, value); }
        }
        Employee fEmployee;
        [Association(@"DeviceLoginReferencesEmployee")]
        public Employee Employee
        {
            get { return fEmployee; }
            set { SetPropertyValue<Employee>(nameof(Employee), ref fEmployee, value); }
        }
        Device fDevice;
        [Association(@"DeviceLoginReferencesDevice")]
        public Device Device
        {
            get { return fDevice; }
            set { SetPropertyValue<Device>(nameof(Device), ref fDevice, value); }
        }
        string fToken;
        public string Token
        {
            get { return fToken; }
            set { SetPropertyValue<string>(nameof(Token), ref fToken, value); }
        }
        [Association(@"TransactionReferencesDeviceLogin")]
        public XPCollection<Transaction> Transactions { get { return GetCollection<Transaction>(nameof(Transactions)); } }
    }

}
