//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Epay3.Module.BusinessObjects.EpayDataModel
{

    public partial class ItemPermission : XPObject
    {
        Customer fCustomer;
        [Association(@"ItemPermissionReferencesCustomer")]
        public Customer Customer
        {
            get { return fCustomer; }
            set { SetPropertyValue<Customer>(nameof(Customer), ref fCustomer, value); }
        }
        TransactionItem fTransactionItem;
        [Association(@"ItemPermissionReferencesTransactionItem")]
        public TransactionItem TransactionItem
        {
            get { return fTransactionItem; }
            set { SetPropertyValue<TransactionItem>(nameof(TransactionItem), ref fTransactionItem, value); }
        }
        bool? fPermission;
        public bool? Permission
        {
            get { return fPermission; }
            set { SetPropertyValue<bool?>(nameof(Permission), ref fPermission, value); }
        }
        bool fActive;
        public bool Active
        {
            get { return fActive; }
            set { SetPropertyValue<bool>(nameof(Active), ref fActive, value); }
        }
    }

}
