//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Epay3.Module.BusinessObjects.EpayDataModel
{

    public partial class LocationCard : XPObject
    {
        Card fCard;
        [Association(@"LocationCardReferencesCard")]
        public Card Card
        {
            get { return fCard; }
            set { SetPropertyValue<Card>(nameof(Card), ref fCard, value); }
        }
        Location fLocation;
        [Association(@"CustomerLocationReferencesLocation")]
        public Location Location
        {
            get { return fLocation; }
            set { SetPropertyValue<Location>(nameof(Location), ref fLocation, value); }
        }
        DateTime fOpenedAt;
        public DateTime OpenedAt
        {
            get { return fOpenedAt; }
            set { SetPropertyValue<DateTime>(nameof(OpenedAt), ref fOpenedAt, value); }
        }
        DateTime fClosedAt;
        public DateTime ClosedAt
        {
            get { return fClosedAt; }
            set { SetPropertyValue<DateTime>(nameof(ClosedAt), ref fClosedAt, value); }
        }
        Employee fOpenedBy;
        [Association(@"LocationCardReferencesEmployee")]
        public Employee OpenedBy
        {
            get { return fOpenedBy; }
            set { SetPropertyValue<Employee>(nameof(OpenedBy), ref fOpenedBy, value); }
        }
        DeviceLogin fDeviceLogin;
        public DeviceLogin DeviceLogin
        {
            get { return fDeviceLogin; }
            set { SetPropertyValue<DeviceLogin>(nameof(DeviceLogin), ref fDeviceLogin, value); }
        }
        [Association(@"OrderReferencesLocationCard")]
        public XPCollection<Order> Orders { get { return GetCollection<Order>(nameof(Orders)); } }
    }

}
