//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Epay3.Module.BusinessObjects.EpayDataModel
{

    [NonPersistent]
    public partial class NPNewCharge : XPObject
    {
        TransactionItem fItem;
        public TransactionItem Item
        {
            get { return fItem; }
            set { SetPropertyValue<TransactionItem>(nameof(Item), ref fItem, value); }
        }
        DateTime fStart;
        public DateTime Start
        {
            get { return fStart; }
            set { SetPropertyValue<DateTime>(nameof(Start), ref fStart, value); }
        }
        DateTime fEnd;
        public DateTime End
        {
            get { return fEnd; }
            set { SetPropertyValue<DateTime>(nameof(End), ref fEnd, value); }
        }
        decimal fQuantity;
        public decimal Quantity
        {
            get { return fQuantity; }
            set { SetPropertyValue<decimal>(nameof(Quantity), ref fQuantity, value); }
        }
    }

}
