//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Epay3.Module.BusinessObjects.EpayDataModel
{

    [DeferredDeletion(false)]
    public partial class OrderDetail : XPObject
    {
        Order fOrder;
        [Association(@"OrderDetailReferencesOrder")]
        public Order Order
        {
            get { return fOrder; }
            set { SetPropertyValue<Order>(nameof(Order), ref fOrder, value); }
        }
        TransactionItem fTransactionItem;
        [Association(@"OrderDetailReferencesTransactionItem")]
        public TransactionItem TransactionItem
        {
            get { return fTransactionItem; }
            set { SetPropertyValue<TransactionItem>(nameof(TransactionItem), ref fTransactionItem, value); }
        }
        TransactionDetail fTransactionDetail;
        [DevExpress.Persistent.Base.VisibleInListView(false), DevExpress.Persistent.Base.VisibleInDetailView(false)]
        public TransactionDetail TransactionDetail
        {
            get { return fTransactionDetail; }
            set { SetPropertyValue<TransactionDetail>(nameof(TransactionDetail), ref fTransactionDetail, value); }
        }
        TransactionDetail fCancelTransactionDetail;
        [DevExpress.Persistent.Base.VisibleInListView(false), DevExpress.Persistent.Base.VisibleInDetailView(false)]
        public TransactionDetail CancelTransactionDetail
        {
            get { return fCancelTransactionDetail; }
            set { SetPropertyValue<TransactionDetail>(nameof(CancelTransactionDetail), ref fCancelTransactionDetail, value); }
        }
        decimal fQuantity;
        public decimal Quantity
        {
            get { return fQuantity; }
            set { SetPropertyValue<decimal>(nameof(Quantity), ref fQuantity, value); }
        }
        Station fStation;
        [Association(@"OrderDetailReferencesStation")]
        public Station Station
        {
            get { return fStation; }
            set { SetPropertyValue<Station>(nameof(Station), ref fStation, value); }
        }
        Epay3.Module.BusinessObjects.EOrderStatus fStatus;
        public Epay3.Module.BusinessObjects.EOrderStatus Status
        {
            get { return fStatus; }
            set { SetPropertyValue<Epay3.Module.BusinessObjects.EOrderStatus>(nameof(Status), ref fStatus, value); }
        }
    }

}
