//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Epay3.Module.BusinessObjects.EpayDataModel
{

    [DeferredDeletion(false)]
    public partial class Order : XPObject
    {
        DateTime fDate;
        public DateTime Date
        {
            get { return fDate; }
            set { SetPropertyValue<DateTime>(nameof(Date), ref fDate, value); }
        }
        Customer fCustomer;
        [Association(@"OrderReferencesCustomer")]
        public Customer Customer
        {
            get { return fCustomer; }
            set { SetPropertyValue<Customer>(nameof(Customer), ref fCustomer, value); }
        }
        Epay3.Module.BusinessObjects.EOrderStatus fStatus;
        public Epay3.Module.BusinessObjects.EOrderStatus Status
        {
            get { return fStatus; }
            set { SetPropertyValue<Epay3.Module.BusinessObjects.EOrderStatus>(nameof(Status), ref fStatus, value); }
        }
        Transaction fTransaction;
        [DevExpress.Persistent.Base.VisibleInListView(false), DevExpress.Persistent.Base.VisibleInDetailView(false)]
        public Transaction Transaction
        {
            get { return fTransaction; }
            set { SetPropertyValue<Transaction>(nameof(Transaction), ref fTransaction, value); }
        }
        Epay3.Module.BusinessObjects.EOrderType fType;
        public Epay3.Module.BusinessObjects.EOrderType Type
        {
            get { return fType; }
            set { SetPropertyValue<Epay3.Module.BusinessObjects.EOrderType>(nameof(Type), ref fType, value); }
        }
        LocationCard fLocationCard;
        [Association(@"OrderReferencesLocationCard")]
        public LocationCard LocationCard
        {
            get { return fLocationCard; }
            set { SetPropertyValue<LocationCard>(nameof(LocationCard), ref fLocationCard, value); }
        }
        [Association(@"OrderDetailReferencesOrder")]
        public XPCollection<OrderDetail> OrderDetails { get { return GetCollection<OrderDetail>(nameof(OrderDetails)); } }
    }

}
