//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Epay3.Module.BusinessObjects.EpayDataModel
{

    [DeferredDeletion(false)]
    public partial class RegistrationRequest : XPObject
    {
        string fVerificationCode;
        public string VerificationCode
        {
            get { return fVerificationCode; }
            set { SetPropertyValue<string>(nameof(VerificationCode), ref fVerificationCode, value); }
        }
        DateTime fDateSent;
        public DateTime DateSent
        {
            get { return fDateSent; }
            set { SetPropertyValue<DateTime>(nameof(DateSent), ref fDateSent, value); }
        }
        string fIpAddress;
        public string IpAddress
        {
            get { return fIpAddress; }
            set { SetPropertyValue<string>(nameof(IpAddress), ref fIpAddress, value); }
        }
        DateTime fDateConsumed;
        public DateTime DateConsumed
        {
            get { return fDateConsumed; }
            set { SetPropertyValue<DateTime>(nameof(DateConsumed), ref fDateConsumed, value); }
        }
        Customer fCustomer;
        [Association(@"RegistrationRequestReferencesCustomer")]
        public Customer Customer
        {
            get { return fCustomer; }
            set { SetPropertyValue<Customer>(nameof(Customer), ref fCustomer, value); }
        }
    }

}
