//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Epay3.Module.BusinessObjects.EpayDataModel
{

    [DeferredDeletion(false)]
    public partial class Site : XPObject
    {
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        int fSlot;
        public int Slot
        {
            get { return fSlot; }
            set { SetPropertyValue<int>(nameof(Slot), ref fSlot, value); }
        }
        string fRegistrationCode;
        public string RegistrationCode
        {
            get { return fRegistrationCode; }
            set { SetPropertyValue<string>(nameof(RegistrationCode), ref fRegistrationCode, value); }
        }
        int fOrderCooldownTime;
        public int OrderCooldownTime
        {
            get { return fOrderCooldownTime; }
            set { SetPropertyValue<int>(nameof(OrderCooldownTime), ref fOrderCooldownTime, value); }
        }
        int fMinimumBalanceLimit;
        public int MinimumBalanceLimit
        {
            get { return fMinimumBalanceLimit; }
            set { SetPropertyValue<int>(nameof(MinimumBalanceLimit), ref fMinimumBalanceLimit, value); }
        }
        bool fFeatureCustomerMenu;
        public bool FeatureCustomerMenu
        {
            get { return fFeatureCustomerMenu; }
            set { SetPropertyValue<bool>(nameof(FeatureCustomerMenu), ref fFeatureCustomerMenu, value); }
        }
        bool fFeatureLoginWithCard;
        public bool FeatureLoginWithCard
        {
            get { return fFeatureLoginWithCard; }
            set { SetPropertyValue<bool>(nameof(FeatureLoginWithCard), ref fFeatureLoginWithCard, value); }
        }
        bool fFeatureCustomerPortal;
        public bool FeatureCustomerPortal
        {
            get { return fFeatureCustomerPortal; }
            set { SetPropertyValue<bool>(nameof(FeatureCustomerPortal), ref fFeatureCustomerPortal, value); }
        }
        bool fFeatureKiosk;
        public bool FeatureKiosk
        {
            get { return fFeatureKiosk; }
            set { SetPropertyValue<bool>(nameof(FeatureKiosk), ref fFeatureKiosk, value); }
        }
        bool fFeatureChargeOnline;
        public bool FeatureChargeOnline
        {
            get { return fFeatureChargeOnline; }
            set { SetPropertyValue<bool>(nameof(FeatureChargeOnline), ref fFeatureChargeOnline, value); }
        }
        bool fFeatureCardBalanceTransfer;
        public bool FeatureCardBalanceTransfer
        {
            get { return fFeatureCardBalanceTransfer; }
            set { SetPropertyValue<bool>(nameof(FeatureCardBalanceTransfer), ref fFeatureCardBalanceTransfer, value); }
        }
        bool fFeatureShopList;
        public bool FeatureShopList
        {
            get { return fFeatureShopList; }
            set { SetPropertyValue<bool>(nameof(FeatureShopList), ref fFeatureShopList, value); }
        }
        decimal fTransactionFee;
        public decimal TransactionFee
        {
            get { return fTransactionFee; }
            set { SetPropertyValue<decimal>(nameof(TransactionFee), ref fTransactionFee, value); }
        }
        decimal fTransactionMonthlyLimit;
        public decimal TransactionMonthlyLimit
        {
            get { return fTransactionMonthlyLimit; }
            set { SetPropertyValue<decimal>(nameof(TransactionMonthlyLimit), ref fTransactionMonthlyLimit, value); }
        }
        int fTimezone;
        public int Timezone
        {
            get { return fTimezone; }
            set { SetPropertyValue<int>(nameof(Timezone), ref fTimezone, value); }
        }
        decimal fLatitude;
        public decimal Latitude
        {
            get { return fLatitude; }
            set { SetPropertyValue<decimal>(nameof(Latitude), ref fLatitude, value); }
        }
        decimal fLongitude;
        public decimal Longitude
        {
            get { return fLongitude; }
            set { SetPropertyValue<decimal>(nameof(Longitude), ref fLongitude, value); }
        }
        int fRadiusMeter;
        public int RadiusMeter
        {
            get { return fRadiusMeter; }
            set { SetPropertyValue<int>(nameof(RadiusMeter), ref fRadiusMeter, value); }
        }
        int fCustomerProvisionTime;
        public int CustomerProvisionTime
        {
            get { return fCustomerProvisionTime; }
            set { SetPropertyValue<int>(nameof(CustomerProvisionTime), ref fCustomerProvisionTime, value); }
        }
        int fWaitressProvisionTime;
        public int WaitressProvisionTime
        {
            get { return fWaitressProvisionTime; }
            set { SetPropertyValue<int>(nameof(WaitressProvisionTime), ref fWaitressProvisionTime, value); }
        }
        bool fNotifyCustomerForTransaction;
        public bool NotifyCustomerForTransaction
        {
            get { return fNotifyCustomerForTransaction; }
            set { SetPropertyValue<bool>(nameof(NotifyCustomerForTransaction), ref fNotifyCustomerForTransaction, value); }
        }
        bool fEnableRemoteOrders;
        public bool EnableRemoteOrders
        {
            get { return fEnableRemoteOrders; }
            set { SetPropertyValue<bool>(nameof(EnableRemoteOrders), ref fEnableRemoteOrders, value); }
        }
        bool fEnableLocationOrders;
        public bool EnableLocationOrders
        {
            get { return fEnableLocationOrders; }
            set { SetPropertyValue<bool>(nameof(EnableLocationOrders), ref fEnableLocationOrders, value); }
        }
    }

}
