//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Epay3.Module.BusinessObjects.EpayDataModel
{

    [DeferredDeletion(false)]
    public partial class StationItem : XPObject
    {
        Station fStation;
        [Association(@"StationItemReferencesStation")]
        public Station Station
        {
            get { return fStation; }
            set { SetPropertyValue<Station>(nameof(Station), ref fStation, value); }
        }
        TransactionItem fTransactionItem;
        public TransactionItem TransactionItem
        {
            get { return fTransactionItem; }
            set { SetPropertyValue<TransactionItem>(nameof(TransactionItem), ref fTransactionItem, value); }
        }
        int fPreparationTime;
        public int PreparationTime
        {
            get { return fPreparationTime; }
            set { SetPropertyValue<int>(nameof(PreparationTime), ref fPreparationTime, value); }
        }
    }

}
