//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Epay3.Module.BusinessObjects.EpayDataModel
{

    [DeferredDeletion(false)]
    public partial class Transaction : XPObject
    {
        DateTime fDate;
        public DateTime Date
        {
            get { return fDate; }
            set { SetPropertyValue<DateTime>(nameof(Date), ref fDate, value); }
        }
        DateTime fProvisionDate;
        [DevExpress.Persistent.Base.VisibleInListView(false)]
        public DateTime ProvisionDate
        {
            get { return fProvisionDate; }
            set { SetPropertyValue<DateTime>(nameof(ProvisionDate), ref fProvisionDate, value); }
        }
        Card fCard;
        [Association(@"TransactionReferencesCard")]
        public Card Card
        {
            get { return fCard; }
            set { SetPropertyValue<Card>(nameof(Card), ref fCard, value); }
        }
        decimal fAmount;
        public decimal Amount
        {
            get { return fAmount; }
            set { SetPropertyValue<decimal>(nameof(Amount), ref fAmount, value); }
        }
        decimal fOldBalance;
        public decimal OldBalance
        {
            get { return fOldBalance; }
            set { SetPropertyValue<decimal>(nameof(OldBalance), ref fOldBalance, value); }
        }
        decimal fNewBalance;
        public decimal NewBalance
        {
            get { return fNewBalance; }
            set { SetPropertyValue<decimal>(nameof(NewBalance), ref fNewBalance, value); }
        }
        int fCycle;
        [MemberDesignTimeVisibility(false)]
        public int Cycle
        {
            get { return fCycle; }
            set { SetPropertyValue<int>(nameof(Cycle), ref fCycle, value); }
        }
        DeviceLogin fDeviceLogin;
        [Association(@"TransactionReferencesDeviceLogin")]
        public DeviceLogin DeviceLogin
        {
            get { return fDeviceLogin; }
            set { SetPropertyValue<DeviceLogin>(nameof(DeviceLogin), ref fDeviceLogin, value); }
        }
        Device fDevice;
        [Association(@"TransactionReferencesDevice")]
        public Device Device
        {
            get { return fDevice; }
            set { SetPropertyValue<Device>(nameof(Device), ref fDevice, value); }
        }
        Employee fEmployee;
        [Association(@"TransactionReferencesEmployee")]
        public Employee Employee
        {
            get { return fEmployee; }
            set { SetPropertyValue<Employee>(nameof(Employee), ref fEmployee, value); }
        }
        string fSourceAddress;
        public string SourceAddress
        {
            get { return fSourceAddress; }
            set { SetPropertyValue<string>(nameof(SourceAddress), ref fSourceAddress, value); }
        }
        decimal fTotalCharges;
        public decimal TotalCharges
        {
            get { return fTotalCharges; }
            set { SetPropertyValue<decimal>(nameof(TotalCharges), ref fTotalCharges, value); }
        }
        decimal fTotalSales;
        public decimal TotalSales
        {
            get { return fTotalSales; }
            set { SetPropertyValue<decimal>(nameof(TotalSales), ref fTotalSales, value); }
        }
        Epay3.Module.BusinessObjects.EProductType fProductType;
        public Epay3.Module.BusinessObjects.EProductType ProductType
        {
            get { return fProductType; }
            set { SetPropertyValue<Epay3.Module.BusinessObjects.EProductType>(nameof(ProductType), ref fProductType, value); }
        }
        bool fIsCancel;
        public bool IsCancel
        {
            get { return fIsCancel; }
            set { SetPropertyValue<bool>(nameof(IsCancel), ref fIsCancel, value); }
        }
        DateTime fDateEffective;
        [DevExpress.Persistent.Base.VisibleInListView(false)]
        public DateTime DateEffective
        {
            get { return fDateEffective; }
            set { SetPropertyValue<DateTime>(nameof(DateEffective), ref fDateEffective, value); }
        }
        [Association(@"TransactionDetailReferencesTransaction"), Aggregated]
        public XPCollection<TransactionDetail> TransactionDetails { get { return GetCollection<TransactionDetail>(nameof(TransactionDetails)); } }
    }

}
