//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Epay3.Module.BusinessObjects.EpayDataModel
{

    public partial class TransactionItemCategory : XPObject
    {
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        string fImageUrl;
        public string ImageUrl
        {
            get { return fImageUrl; }
            set { SetPropertyValue<string>(nameof(ImageUrl), ref fImageUrl, value); }
        }
        string fIcon;
        public string Icon
        {
            get { return fIcon; }
            set { SetPropertyValue<string>(nameof(Icon), ref fIcon, value); }
        }
        string fCode;
        public string Code
        {
            get { return fCode; }
            set { SetPropertyValue<string>(nameof(Code), ref fCode, value); }
        }
        string fOrder;
        public string Order
        {
            get { return fOrder; }
            set { SetPropertyValue<string>(nameof(Order), ref fOrder, value); }
        }
        [Association(@"TransactionItemReferencesTransactionItemCategory")]
        public XPCollection<TransactionItem> TransactionItems { get { return GetCollection<TransactionItem>(nameof(TransactionItems)); } }
    }

}
